"""
OpenAPI Contract Inspector
--------------------------
Extracts OpenAPI schema from FastAPI app and provides
a clean interface for contract testing.
"""

from app.main import app


def get_openapi_schema():
    """
    Returns the full OpenAPI schema generated by FastAPI.

    This is used for:
    - contract testing
    - schema diffing (future phase)
    - API validation in CI

    Returns:
        dict: OpenAPI schema JSON
    """
    return app.openapi()